### ISSUE TITLE
[BUG] Get Random Spell isn't working

### ISSUE THREAD

**Issue by mnoreke** [p4535992/foundryvtt-better-rolltables#25]
**Module Version:** v2.0.31

The code for getting random spells is commented out. Can we get this working again? For Foundry V11 please. :)

// static async _getRandomSpell(level) {

**Comment by p4535992** [comment]
Is been removed for good reasons because was to system dependent, based on regex and other sutff, and there are more simple ways to accomplish this modules,macros, or apis (on this same module) for accomplish this. The most used solution is to prepare a collection of spells preFiltered with by some attrbiute and create the rolltable,

Try this api [create-a-table-from-a-compendium](https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/wiki/api/api.md#create-a-table-from-a-compendium) or some of the of the context action on the compendium directory 

![](https://github.com/p4535992/foundryvtt-better-rolltables/raw/master/wiki/img/context_menu_compendium.png)

**Comment by mnoreke** [comment]
Understood.

Perhaps the Wiki should be updated to reflect this, specifically:
https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/wiki/FAQ.md

**Comment by p4535992** [comment]
> Understood.
> 
> Perhaps the Wiki should be updated to reflect this, specifically: https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/wiki/FAQ.md

Any help on the documentation front is welcome
